# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_dev
    ports:
    - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musicshare_development
    restart: unless-stopped

volumes:
  db_data:
